# Generated by Django 5.0.7 on 2024-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='sankalp'),
        ),
    ]
